sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 8.0
services: docker
before_install:
  - cd 19_RestwithASPNETUdemy_AddingDockerSupport
  - echo "We are in the right folder"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy:latest cfmalm/rest-with-asp-net-udemy:latest;
    docker tag rest-with-asp-net-udemy-db:latest cfmalm/rest-with-asp-net-udemy-db:latest;
    docker push cfmalm/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push cfmalm/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
  on:
    branch: main
notifications:
  email: false
    